### ISSUE TITLE
Check Against Database

### ISSUE THREAD

**Issue by ancgate** [Allen-Wei/RulesEngine#1]
HI Allen-Wei,

This is a wonderful work you did and thank you. This is not an issue, but rather how check a value against a database. For example

 rules.For<Person>()
                .Setup(p=> p.MemberIdentification).MustEqual(GetIdentification(MemberIdentification)).WithMessage("This Identification doesn't exist");

The idea is to pass the value from p.MemberIdentification to the GetIdentification method. 
If you need more clarification, let me know. Thanks

**Comment by ancgate** [comment]
The best way I found so far is to create extension method. But if you can add a feature as a I mentioned before to the Library, it would be a plus.

**Comment by alanwei43** [comment]
@ancgate Thank your for your suggestion. Show your clarification sample code please. ( Forgive my poor English.)

**Comment by ancgate** [comment]
HI Allen, sorry for the late answer. This is my workaround. If you have more questions, feel free to contact me

public static class DatabaseExtension {

 public static DataServiceProvider = new DataServiceProvider();

 public static string GetUsername(this Person value)
 
     var a = DataServiceProvider.GetUsername(value);
	 
	 if (a!=null) {
	 
	    return value;
	 }
	 return
 
}

public class Person : IValidationDefinition
    {
        private const string username = "username already Exist";
        private const string emptyUsername = "The Username should not be empty";
		private const string password = "The password should match";
		private const string regex = "XXXXXXXXXXXX";

        
        public void Define(Engine rules)
        {
            rules.For<Person>()
                .Setup(p => p.Username).MustNotEqual(p => p.Username.GetUsername()).WithMessage(username)
                .Setup(p => p.Password).MustMatchRegex(regex).WithMessage(password);
        }
    }

**Comment by ancgate** [comment]
I will be using the extensions method so far.
